-- Seed AI Academy Documents

INSERT INTO docs (slug, title, category, sort_order, description, content, display_in_areslib, display_in_math_corner, display_in_science_corner)
VALUES 
(
  'ai-101-biology', 
  'The Biological Neuron', 
  'AI 101', 
  1, 
  'Understand the biological inspiration behind artificial neural networks.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Before we can build Artificial Intelligence, we must understand how biological intelligence works. A biological neuron consists of dendrites (inputs), a soma (cell body), and an axon (output). Play with the simulation below to see how mathematical models attempt to mimic this biological process:"}]},{"type":"interactiveComponent","attrs":{"name":"nn-biology"}},{"type":"paragraph","content":[{"type":"text","text":"Notice how the weights and biases warp the input values."}]}]}',
  0, 0, 1
),
(
  'ai-101-basics', 
  'Neural Network Basics', 
  'Neural Networks', 
  1, 
  'Learn how neurons connect together to form networks.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"By connecting multiple perceptrons together, we create a Neural Network capable of solving non-linear problems. Observe the training process of a multi-layer perceptron below:"}]},{"type":"interactiveComponent","attrs":{"name":"nn-intro"}},{"type":"paragraph","content":[{"type":"text","text":"The network adjusts its weights using Backpropagation to minimize the error."}]}]}',
  0, 0, 1
),
(
  'ai-101-activation', 
  'Activation Functions', 
  'Neural Networks', 
  2, 
  'Visualize how non-linear functions warp output spaces.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Without activation functions, a neural network is just a giant linear regression model. Activation functions like ReLU, Sigmoid, and Tanh introduce non-linearity."}]},{"type":"interactiveComponent","attrs":{"name":"nn-activation"}},{"type":"paragraph","content":[{"type":"text","text":"Try selecting different functions and observing how the output maps to the input space."}]}]}',
  0, 0, 1
),
(
  'ai-101-cnn', 
  'Convolutional Neural Networks', 
  'Machine Vision', 
  1, 
  'Slide filters across images to extract visual features.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Images are too large to process pixel-by-pixel with standard dense layers. Instead, CNNs use sliding filters (kernels) to detect edges, textures, and shapes."}]},{"type":"interactiveComponent","attrs":{"name":"nn-cnn"}},{"type":"paragraph","content":[{"type":"text","text":"Notice how the Vertical Edge filter highlights different pixels than the Horizontal Edge filter."}]}]}',
  0, 0, 1
),
(
  'ai-101-vision', 
  'Machine Vision Pipelines', 
  'Machine Vision', 
  2, 
  'How CNNs are used in robotics and FRC.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"We use Machine Vision in FRC to detect AprilTags and game pieces. The underlying technology relies on Convolutional networks."}]},{"type":"interactiveComponent","attrs":{"name":"nn-vision"}},{"type":"paragraph","content":[{"type":"text","text":"The bounding box is generated by a regression head attached to the CNN backbone."}]}]}',
  0, 0, 1
),
(
  'ai-101-llm', 
  'LLMs & Attention', 
  'Generative AI', 
  1, 
  'How Transformers revolutionized Natural Language Processing.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Large Language Models (LLMs) use the Attention mechanism to weigh the importance of different words in a sequence, rather than processing them strictly left-to-right."}]},{"type":"interactiveComponent","attrs":{"name":"nn-llm"}},{"type":"paragraph","content":[{"type":"text","text":"The thicker the line in the simulation, the more attention is being paid to that specific token."}]}]}',
  0, 0, 1
),
(
  'ai-101-diffusion', 
  'Diffusion Models', 
  'Generative AI', 
  2, 
  'How AI generates art by removing noise.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Diffusion models are trained by slowly adding noise to an image until it is pure static. The network then learns to reverse this process, predicting the noise and subtracting it."}]},{"type":"interactiveComponent","attrs":{"name":"nn-diffusion"}},{"type":"paragraph","content":[{"type":"text","text":"Click Denoise to watch the model iteratively remove noise to generate the image."}]}]}',
  0, 0, 1
),
(
  'ai-101-rl', 
  'Reinforcement Learning', 
  'Reinforcement Learning', 
  1, 
  'Training agents via rewards and punishments.', 
  '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Unlike Supervised Learning, Reinforcement Learning (RL) agents learn by interacting with an environment and receiving rewards or penalties."}]},{"type":"interactiveComponent","attrs":{"name":"nn-rl"}},{"type":"paragraph","content":[{"type":"text","text":"Watch the Q-values (represented by the brightness of the blue squares) update as the agent explores the maze."}]}]}',
  0, 0, 1
)
ON CONFLICT(slug) DO UPDATE SET 
  title=excluded.title, 
  category=excluded.category, 
  description=excluded.description, 
  content=excluded.content, 
  display_in_math_corner=excluded.display_in_math_corner, 
  display_in_science_corner=excluded.display_in_science_corner;
