#!/usr/bin/env node
/**
 * Auto-Generate Sim Registry
 *
 * Reads simRegistry.json and generates:
 * 1. Lazy import declarations for all sims
 * 2. SIM_COMPONENTS mapping object
 * 3. SIM_TAG_NAMES array
 *
 * This script keeps DocsMarkdownRenderer.tsx and TiptapRenderer.tsx
 * in sync with the actual sims in the codebase.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

interface SimInfo {
  id: string;
  name: string;
  path: string;
  requiresContext: boolean;
}

interface SimRegistry {
  simulators: SimInfo[];
}

// Read simRegistry.json
function readSimRegistry(): SimRegistry {
  const registryPath = path.join(ROOT, 'src/sims/simRegistry.json');
  const content = fs.readFileSync(registryPath, 'utf-8');
  return JSON.parse(content);
}

// Convert sim ID to lowercase tag name for markdown
// The tag name is simply the lowercase id
function toComponentTagName(id: string): string {
  return id.toLowerCase();
}

// Generate lazy imports
function generateLazyImports(registry: SimRegistry): string {
  const imports: string[] = [];

  for (const sim of registry.simulators) {
    const folder = sim.path.replace('./', '');
    // PascalCase component name from id
    const componentName = sim.id;
    imports.push(`const ${componentName} = lazy(() => import("../../sims/${folder}"));`);
  }

  return imports.join('\n');
}

// Generate SIM_COMPONENTS mapping
function generateSimComponents(registry: SimRegistry): string {
  const entries: string[] = [];

  for (const sim of registry.simulators) {
    const componentName = sim.id;
    const tagName = toComponentTagName(sim.id);
    entries.push(`  ${tagName}: ${componentName},`);
  }

  return `const SIM_COMPONENTS: Record<string, React.ComponentType<any>> = {\n${entries.join('\n')}\n};`;
}

// Generate complete registry file content
function generateRegistryContent(): string {
  const registry = readSimRegistry();
  const lazyImports = generateLazyImports(registry);
  const simComponents = generateSimComponents(registry);

  return `// Auto-generated by scripts/generate-sim-registry.ts
// DO NOT EDIT MANUALY - run: npm run generate:sims

import { lazy } from "react";

// ── Lazy-loaded Simulators ─────────────────────────────────────────────
${lazyImports}

// ── Sim Component Registry ───────────────────────────────────────────────
// Maps sim component IDs to their lazy-loaded components
// Tag names are lowercased versions of the component IDs
${simComponents}

// Generate tag names and component mappings from SIM_COMPONENTS
const SIM_TAG_NAMES = Object.keys(SIM_COMPONENTS);

export { SIM_COMPONENTS, SIM_TAG_NAMES };
`;
}

// Write the generated file
function writeRegistryFile(content: string): void {
  const outputPath = path.join(ROOT, 'src/components/generated/sim-registry.ts');
  const outputDir = path.dirname(outputPath);

  // Ensure directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`✅ Generated: ${outputPath}`);
}

// Main execution
function main(): void {
  try {
    console.log('🔨 Generating sim registry...');
    const content = generateRegistryContent();
    writeRegistryFile(content);
    console.log(`📦 Registered ${readSimRegistry().simulators.length} sims`);
  } catch (error) {
    console.error('❌ Error generating sim registry:', error);
    process.exit(1);
  }
}

main();
